import Foundation
import Version

enum PlaygroundGeneratorError: Error {
    case unexpectedScheme(String)
    case unknownAction(String)
    case invalidURL(URL)
    case missingDependenciesQuery
    case notYetReleased
}

extension PlaygroundGeneratorError: CustomStringConvertible {
    var description: String {
        switch self {
        case .unexpectedScheme(let scheme): "The scheme \"\(scheme)\" is unexpected."
        case .unknownAction(let action): "The action \"\(action)\" is not supported."
        case .invalidURL(let url): "\(url) is invalid."
        case .missingDependenciesQuery: "The query \"dependencies\" is missing."
        case .notYetReleased: "The package is not yet released."
        }
    }
}

struct PlaygroundGenerator {
    let packageName: String
    let packageURL: URL
    let latestVersion: String

    init(url: URL) async throws {
        guard let scheme = url.scheme, let host = url.host() else {
            throw PlaygroundGeneratorError.invalidURL(url)
        }
        guard scheme == "spi-playgrounds" else {
            throw PlaygroundGeneratorError.unexpectedScheme(scheme)
        }
        guard host == "open" else { throw PlaygroundGeneratorError.unknownAction(host) }
        guard let components = URLComponents(url: url, resolvingAgainstBaseURL: false) else {
            throw PlaygroundGeneratorError.invalidURL(url)
        }
        guard let name = components.queryItems?.first(where: { $0.name == "dependencies" })?.value
        else { throw PlaygroundGeneratorError.missingDependenciesQuery }
        let tagsURL =
            githubAPIBaseURL
            .appending(path: "repos")
            .appending(path: name)
            .appending(path: "git/matching-refs/tags")
        let (data, _) = try await URLSession.shared.data(from: tagsURL)
        let tag = try JSONDecoder().decode(GitReferences.self, from: data).lazy
            .map(\.ref)
            .map { $0.trimmingPrefix("refs/tags/") }
            .compactMap { Version(tolerant: $0) }
            .filter { $0.prereleaseIdentifiers.isEmpty }
            .max()
        guard let tag else { throw PlaygroundGeneratorError.notYetReleased }
        self.packageName = name
        self.packageURL = githubBaseURL.appending(path: name)
        self.latestVersion = tag.description
    }

    func generate() throws -> URL {
        let manifest = """
            // swift-tools-version: 5.10

            // WARNING:
            // This file is automatically generated.
            // Do not edit it by hand because the contents will be replaced.

            import PackageDescription
            import AppleProductTypes

            let package = Package(
                name: "My App",
                platforms: [
                    .iOS("17.5")
                ],
                products: [
                    .iOSApplication(
                        name: "My App",
                        targets: ["AppModule"],
                        displayVersion: "1.0",
                        bundleVersion: "1",
                        appIcon: .placeholder(icon: .box),
                        accentColor: .presetColor(.blue),
                        supportedDeviceFamilies: [
                            .pad,
                            .phone
                        ],
                        supportedInterfaceOrientations: [
                            .portrait,
                            .landscapeRight,
                            .landscapeLeft,
                            .portraitUpsideDown(.when(deviceFamilies: [.pad]))
                        ]
                    )
                ],
                dependencies: [
                    .package(url: "\(self.packageURL)", from: "\(self.latestVersion)")
                ],
                targets: [
                    .executableTarget(
                        name: "AppModule",
                        dependencies: [
                        ],
                        path: ".",
                        swiftSettings: [
                            .enableUpcomingFeature("BareSlashRegexLiterals")
                        ]
                    )
                ]
            )
            """
        let myApp = """
            import SwiftUI

            @main
            struct MyApp: App {
                var body: some Scene {
                    WindowGroup {
                        ContentView()
                    }
                }
            }
            """
        let contentView = """
            import SwiftUI

            struct ContentView: View {
                var body: some View {
                    Text("Hello, world!")
                }
            }
            """
        let fm = FileManager.default
        let tmp = URL.temporaryDirectory
        let packageURL = tmp.appending(path: "My App.swiftpm")
        if fm.fileExists(atPath: packageURL.path(percentEncoded: false)) {
            try fm.removeItem(at: packageURL)
        }
        try fm.createDirectory(
            at: packageURL,
            withIntermediateDirectories: false
        )
        try manifest.write(
            to: packageURL.appending(path: "Package.swift"),
            atomically: true,
            encoding: .utf8
        )
        try myApp.write(
            to: packageURL.appending(path: "MyApp.swift"),
            atomically: true,
            encoding: .utf8
        )
        try contentView.write(
            to: packageURL.appending(path: "ContentView.swift"),
            atomically: true,
            encoding: .utf8
        )
        return packageURL
    }
}
